language: node_js
node_js:
    - 14
env:
    - NODE_ENV=production
script:
    - npm test
    - npm run build
deploy:
    provider: firebase
    token:
        secure: TOKUvDYk4paMw63OqeKVk+KVnWdCwqDOtVniiaQiWW3CqxHilZ3ilZRsZcO64omkSsOfC8OGe+KVk+KUlMKww7vilIzDnCl+wqLilZbilIIpw7filpAL4pSALAfiiaRMQ8Kj4oygKuKVm+KVmcOvd3fOqRvilpDilabiloxNUjQUdeKVoiIj4pSY4pSAaOKInjo34oieditZ4pSMaB0Vwr/OscKhw7niiYhBVSnilZgjCMOkwqx3zrQtw6sINHrOpj/Dol0P4pWVcOKVl+KJoXjilasW4paITeKVk+KJpMOcKCEn4oyQcMO5w7vilanCoMOhw6nDhM+A4oiZA8OmZyVrwqzilozilpNGfz/DusKxB+KWiDXCu8Ocz4bDr8K9NcO2w4RHMeKWk3IgDQoJw65b4pWSzqPiiKl34pagW86p4pWS4pSsEeKJoRZBMRYw4pSYR8Ki4oG/MEU4O+KVkOKWgMK9wqU0DQrCrE81wqsXR+KImlwJKWfDhj/ilpLDsycXG+KVpCVGzqNdw67ilajDhxbilZnDp+KIqcK34pWiGOKWgEBiw6jCssOqw6sXfh9WO+KVplrDh86mw5Euw6kuKQvDvGkVBeKVnBjDlsOk4paTdmjiiaUw4pWUw6HilpBk4pWi4pWcFUjilohzbVnCuuKVqeKWkuKVpyLDkVDilZ5iZGTPhM60w7vCusOyWcOnw4k5R+KVlwMITwIvzqYe4pWQJinDhy06Y+KJoSLilIzDpQ8ASVjigb/OmAgx4pWcOcOu4pWfCSfilaTilogXMeKUvCQ2IHBZ4oyg4pWiUwDiiJ5zZHQ+THp6w6HDh8ORbeKVlhjiiYjilaHCtT4pViTDtH7iiaXilILilLxqfV5Q4pSkwqoVRsOkw63ilZ7iiJlzw7Qzz4Yew7bilJjilIArDMKsLsOpPjoi4oKnw6V+fgEWYDRb4paSeeKVmx9tAUJbwqDPhg9w4pWlM+KVlFdCP+KImuKVqsORwrLCo8OyZkodfTTilLwE4paQCMKsNs6TzqMNCn5cxpIBzrXCt+KUjAMpLHdi4paQOOKVlVnilatfH33ilad9LigL4pWUYgPCteKCp+KUjOKMkOKVp86pwrXDpCPCo+KUkMOizqbDh21WFeKVpH3ilZrDoDzDrsO2eBgSwrc0w7figqdf4pWSw4QNCg==
    edge: true
