language: node_js
node_js:
    - 14
env:
    - NODE_ENV=production
deploy:
    provider: firebase
    token: dRHlXM0Ufmkah1XkjavM3UI4gMnl6NJUa0J00zX2+0B223rqrS9QomJ0n8pN4Sn65NjeIm0H0hDNH9yEyfS8YG2GdClwYISQPW0Enup078pGNQB7r7uOSt+6G2X0ksCj1nqmsqYbY1xRf9ZYGjbSctNf3qCoKR7qSAvS1QK42r9Zk+e8VNxkmr12aC9qJDR4c2iSX71znxbvfhJkCV3uev3hf8rbYMw5A+0sx4rO1HYBGmOzR1rlPSK6E8I6YMVGcO/O2LtU8NhAf79RNvPi1mHdmMFnqRgiCYQH9nz4NTqQZJoxQe7HreVEUop616RumsdaBqKl3Vdyq2slBs3FkALSoAhpvFRcC+1KSz8/QkBx65q/c4GgKvR98Nc2x9foMlwa0+4zUMe4KyETM51bnTVVHpXQgn1Kn56nIiRJ+ASevARuDdMz/VB5f7OAZzB8+DrhTqxytadlBn52eaNJWMp1zOhAaJnmf4OUgqmgMQKVrsmVafDb1WKQ+KfaBbootQg/Z1/0aCnL1AyJYEvYLuVlBTvc3+BUOssAFbD8M+VZhZMWWaXWD5IkNjk9yMxMzGMo+kkN76qdCplH3G4TQog6PsDevDxD7sSh9daKiEXLrIN6sZHDZC0gbOkhvV9WKGPJaUtFr1tMVGCj2WVVTyHif5twPaqkgZ21RZ0Xkzc=
    edge: true
