version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test -- --reporters=jest-junit
  store_test_results:
    path: junit.xml
workflows:
  build-and-test:
    jobs:
      - build-and-test
